"""Add related articles relationship

Revision ID: 5d6af584c494
Revises: 9809a16a1c24
Create Date: 2025-04-02 09:53:52.750996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6af584c494'
down_revision = '9809a16a1c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_articles',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['related_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'related_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_articles')
    # ### end Alembic commands ###
